export const Lang ={
       "en":{
            Signin:"Sign In",
            Signinnow:"Sign In Now",
            SignUp:"Sign Up",
            SignUpnow:"Sign Up Now",
            Signout:"Sign Out",
            NewNetflix:"New to Netflix ?",
            Alreadyaccount:"Already Registerd ?",
            fullname:"Full Name",
            email:"Email",
            password:"Password",
            confirmpassword:"Confirm Password",
            Home:"Home",
            Search:"Search",
            SearchGPTplaceholder:"What would you like to watch today ?",
            SearchGPTpage:"Search Movies",




       },
       "Hindi":{
        Signin:"दाखिल करना",
        Signinnow:"अब साइन इन करो",
            SignUp:"साइन अप करें ",
            SignUpnow:"अभी साइनअप करें",
            Signout:"साइन आउट",
            NewNetflix:"नेटफ्लिक्स पर नए हैं ? ",
            Alreadyaccount:"पहले से ही पंजीकृत ?",
            fullname:"पूरा नाम",
            email:"ईमेल",
            password:"पासवर्ड",
            confirmpassword:"पासवर्ड की पुष्टि कीजिये",
            Home:"घर",
            Search:"खोज",
            SearchGPTplaceholder:"आज आप क्या देखना चाहेंगे ?",
            SearchGPTpage:"फ़िल्में खोजें",
    
    },
       "Tamil":{
        Signin:"உள்நுழையவும்",
        Signinnow:"இப்போது உள்நுழையவும்",
            SignUp:"பதிவு செய்யவும்",
            SignUpnow:"இப்பொது பதிவு செய்",
            Signout:"வெளியேறு",
            NewNetflix:"Netflix க்கு புதியதா ?",
            Alreadyaccount:"ஏற்கனவே பதிவு செய்யப்பட்டுள்ளதா ?",
            fullname:"முழு பெயர்",
            email:"மின்னஞ்சல்",
            password:"கடவுச்சொல்",
            confirmpassword:"கடவுச்சொல்லை உறுதிப்படுத்தவும்",
            Home:"வீடு",
            Search:"தேடு",
            SearchGPTplaceholder:"இன்று நீங்கள் எதைப் பார்க்க விரும்புகிறீர்கள் ?",
            SearchGPTpage:"திரைப்படங்களைத் தேடுங்கள்",

   },
   "Arabic":{
    Signin:"تسجيل الدخول",
    Signinnow:"قم بتسجيل دخولك الآن ",
        SignUp:"اشتراك",
        SignUpnow:"أفتح حساب الأن",
        Signout:"خروج",
        NewNetflix:"هل أنت جديد على Netflix ؟",
        Alreadyaccount:"مسجل بالفعل ؟",
        fullname:"الاسم الكامل",
        email:"بريد إلكتروني",
        password:"كلمة المرور",
        confirmpassword:"تأكيد كلمة المرور",
        Home:"بيت",
        Search:"يبحث",
        SearchGPTplaceholder:"ماذا تريد أن تشاهد اليوم ؟",
        SearchGPTpage:"بحث الأفلام",

},

"Urdu":{
    Signin:"سائن ان",
    Signinnow:"ابھی سائن ان کریں۔",
        SignUp:"سائن اپ",
        SignUpnow:"ابھی سائن اپ کریں",
        Signout:"باہر جائیں",
        NewNetflix:"Netflix میں نئے ہیں ؟",
        Alreadyaccount:"پہلے سے رجسٹرڈ ہے ؟",
        fullname:"پورا نام",
        email:"ای میل",
        password:"پاس ورڈ",
        confirmpassword:"پاس ورڈ کی تصدیق کریں۔",
        Home:"گھر",
        Search:"تلاش کریں",
        SearchGPTplaceholder:"آج آپ کیا دیکھنا چاہیں گے ؟",
        SearchGPTpage:"بحث الأفلام"

},
}